### ISSUE TITLE
Not working on Samsung Galaxy s9 and android 11 phh gsi

### ISSUE THREAD

**Issue by ciucciodifuoco** [ExpressLuke/phh-magisk-builder#1]
Hi,

i want to report that the magisk installation fails on the latest phh gsi (installed it on samsung galaxy s9). 
In TWRP the installation seems ok, even if at the end the last line says "failed to mount /system_root" in red.

The phone then boots normally, but magisk manager says "This version of magisk manager doesn't support magisk version under 19.0" and it acts like there is no magisk installed at all.

Any hint to fix this isssue? i'll be glad to help in testing a possible resolution.

EDIT: the issue seems related to the GSI rom itself. Basically after installing it twrp isn't able to mount /system anymore, tried with twrp 3.4 and 3.3.1

**Comment by luke-apk** [comment]
This currently doesn't work on Android 11. Magisk requires updates that don't exist yet.
